POST http://localhost:8080/events
Content-Type: application/json

{
    "name": "Test Event for user 2",
    "description": "A test Description for 2 ",
    "location": "A test location",
    "dateTime": "2025-05-10T18:30:00.000Z"
}